services:
  document_reasoner:
    build: .
    container_name: document_reasoner
    networks:
      - python-ntwk
    environment:
      DISPLAY: $WINDOWS_IP:0
      LIBGL_ALWAYS_INDIRECT: 1
    env_file:
      - .env
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - /tmp/.X11-unix:/tmp/.x11-unix:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - python-ntwk
    restart: always

networks:
  python-ntwk:
    driver: bridge

volumes:
  qdrant_data:
